### ISSUE TITLE
Audio via headphone jack is not working by default 

### ISSUE THREAD

**Issue by dheerajv4855** [devboloji/Infinix-Hackintosh-Opencore-Guide#13]
First of all thanks a lot for this amazing post. 
Can you guide me how to add audio device id in configurator 
everything works great even bluetooth headphone 
but onboard audio is not working 
Please give me the steps to configure that

**Comment by devboloji** [comment]
> First of all thanks a lot for this amazing post. 
> Can you guide me how to add audio device id in configurator 
> everything works great even bluetooth headphone 
> but onboard audio is not working 
> Please give me the steps to configure that 

You should mention your device name in your issue. 
If your device is x1, USE opencore configurator, change layoutid in NVRAM as alcid=26 or 99. Try each number, and reboot device then rest RESET NVRAM in boot menu once for every change.

**Comment by dheerajv4855** [comment]
okay I will try.
my device is x1 slim i3 version

**Comment by dheerajv4855** [comment]
what i understood , 
You are talking about Configurator -> NVRAM -> First UUID -> boot_args = alcid=99 or 26.
Thanks for the quick reply.

**Comment by devboloji** [comment]
> what i understood , 
> You are talking about Configurator -> NVRAM -> First UUID -> boot_args = alcid=99 or 26.
> Thanks for the quick reply.

@dheerajv4855 yeah Yeah that's That's what I am saying!!!

**Comment by devboloji** [comment]
@dheerajv4855 use alcid =1 and shutdown your device and RESET NVRAM once and boot into OS.
Then change the alcid=26, shutdown and do the same thing as we done for alcid=1. Report me back if it works..
For slim, audio works.

**Comment by devboloji** [comment]
@dheerajv4855 use alcid =1 and shutdown your device and RESET NVRAM once and boot into OS.
Then change the alcid=26, shutdown and do the same thing as we done for alcid=1. Report me back if it works..
For slim, audio works.

**Comment by dheerajv4855** [comment]
> @dheerajv4855 use alcid =1 and shutdown your device and RESET NVRAM once and boot into OS.
> Then change the alcid=26, shutdown and do the same thing as we done for alcid=1. Report me back if it works..
> For slim, audio works.

did the same process, 
no success,
BTW thanks for your effort you are taking to reply.
I think audio chip used in slim may be different 
how can we find which audio chip is getting used ?
I searched a lot but didn't find the tech spec for this laptop.

**Comment by devboloji** [comment]
@dheerajv4855
Slim users used the efi, they got no issue like you. Let's wait and let the efi be settled. I will tell you what to do next, wait for some time. And you can see your audio module details in windows(device properties). Between, what changes you made in the EFI?

**Comment by dheerajv4855** [comment]
I just changed alcid via opencore configurator that's it in config.plist file

**Comment by devboloji** [comment]
@dheerajv4855 just stick with 26. Lets wait for two weeks to fix itself.. If not report back..

**Comment by dheerajv4855** [comment]
I am using bigsur should I switch to Monterey. may be audio problem will be solved.

**Comment by devboloji** [comment]
@dheerajv4855 better switch to monterey. It may workout.. 😉

**Comment by dheerajv4855** [comment]
> @dheerajv4855 better switch to monterey. It may workout.. 😉

No luck in Monterey also. 
I have bought usb sound card which is working great. 
And that is Better way instead of wasting time on correcting the onboard audio.
Thanks devboloji for this great repo.
Have a coffee from my side.

**Comment by devboloji** [comment]
@dheerajv4855 Thank you for supporting me. I am looking forward to provide the upcoming MacOS as well.
Can you give me the link of the sound card that used!

**Comment by dheerajv4855** [comment]
> @dheerajv4855 Thank you for supporting me. I am looking forward to provide the upcoming MacOS as well.
> Can you provide me the link of the sound card that used!

I bought from Flipkart 
this is the cheap one from Flipkart https://dl.flipkart.com/s/yNCkRMNNNN
but audio quality and mic sound is good.
