### ISSUE TITLE
Issue In Audio

### ISSUE THREAD

**Issue by InfantNixon** [devboloji/Infinix-Hackintosh-Opencore-Guide#14]
I Had A Issue In Input And Output Audio Device,it showing that there is no input and output audio device , so i tried to change a little things in config.plist that caused a another issue ,laptop started rebooting automatically now i started the macos installation again please give me the solution.

Device : Infinix Inbook X1 Slim
Processor : I3 10th gen

**Comment by devboloji** [comment]
@InfantNixon We all know about audio issue on X1 slim. 

Did you try by replacing your EFI with the release EFI.? If not try it and report me back! 

But remember, Every time changing your config, you better try with USB first by booting into via USB and then copy that EFI to your drive.

**Comment by InfantNixon** [comment]
Okk thank u let me try it and ill report to u later

**Comment by InfantNixon** [comment]
Can U Please Send Me Exact Link For Release EFI

**Comment by devboloji** [comment]
@InfantNixon You can check my release page (Releases) in my page or go through the link. [Link](https://github.com/devboloji/Infinix-Hackintosh-Opencore-Guide/releases/tag/OC-0.8.5-EFI-infinix-inbook-series). Go with your MacOS version.

**Comment by InfantNixon** [comment]
I tried those this things in ventura if i tried it with monterey is it possible to solve this problem

**Comment by InfantNixon** [comment]
> @InfantNixon You can check my release page (Releases) in my page or go through the link. [Link](https://github.com/devboloji/Infinix-Hackintosh-Opencore-Guide/releases/tag/OC-0.8.5-EFI-infinix-inbook-series). Go with your MacOS version.

I Tried it again brother,No changes there.same issue

**Comment by InfantNixon** [comment]
> @InfantNixon Ok tell me What did you do in the config.?
> What changes you made to the EFI ?
> From when onwards this issue is happening since installing macos?
> Have you ever faced this issue before ?
> And Do you have some knowledge about hackintoshing?

My issue is only in audio,i tried to change different versions of applealc kext and changed alcid to 22 and also 99 both didn't work for me

**Comment by devboloji** [comment]
@InfantNixon AppleALC is not supported for your x1 slim. So wait for the ALC FIX.
It's like you change something in the expectedly, 
copy the release EFI to the USB and boot from it then replace the EFI in drive of USB. If it's not fixed then you may need to install the Mac OS again.

**Comment by InfantNixon** [comment]
Ok Thank U,Once You Got The ALC Fix Please Upload It On.Im Eagerly Waiting For it Bcoz my Work Is Based On Audio .Im using Logic Pro X

**Comment by devboloji** [comment]
@InfantNixon 
 Yeah, Music production requires Audio. You may need to wait for a long long time for Alc Fix. I too use Logic X for my production songs in inbook X1 working flawlessly . So, I can understand. MacOs is great for This category. So better stick with it. And You better buy a in/out sound device which supports  MacOS  and cheap to buy. One guy Bought for his inbook X2. Its working good. Check my  previous github issues of infinix hackintosh issue about it. You may find any way.!

**Comment by InfantNixon** [comment]
Brother i found something on my bios.that this laptop's audio codec is ALC 274
![Uploading image.jpg…]()

**Comment by devboloji** [comment]
@InfantNixon Ok great, try ALC codecs Each one with alc274. Change alcid of nvram and save it. Use opencore configurator. Do a reset nvram once, if you change alcid eachtime.

**Comment by InfantNixon** [comment]
No fixes brother im currently using my bluetooth earphones and wired audiodevices using soundcard

**Comment by devboloji** [comment]
@InfantNixon that's what I'm saying. The audio broke in x1 slim. So go with sound card or use what you have right now or wait for the alc fix from AppleALC.
I'm closing this issue and you can re-open if found the fix. 
Don't have a good day! Have a great day.

**Comment by phuminsingla** [comment]
![Screen Shot 2565-11-24 at 18 43 17](https://user-images.githubusercontent.com/5608098/203778081-1bd24211-f8fb-4631-beab-64d171a80a72.png)
![Screen Shot 2565-11-24 at 18 43 09](https://user-images.githubusercontent.com/5608098/203778311-86efcd84-14c0-49c5-9ae4-0ca5301dc510.png)
![Screen Shot 2565-11-24 at 18 42 54](https://user-images.githubusercontent.com/5608098/203778341-7a9f179e-b952-4703-bbb7-2ef19d1b7cd7.png)

Infinix X2 i3-1005g1 not show audio. Please help me.

**Comment by devboloji** [comment]
@phuminsingla Try changing a your layout id to 99 and do a reset nvram and then do Shutdown once and  A reboot once one after another. Then lastly change your layout id to 26 then again do Shutdown once and  A reboot once . Thant's it you can do.

**Comment by phuminsingla** [comment]
> @phuminsingla Try changing a your layout id to 99 and do a reset nvram and then do Shutdown once and A reboot once one after another. Then lastly change your layout id to 26 then again do Shutdown once and A reboot once . Thant's it you can do.

Nothing happened
