### ISSUE TITLE
Grey Screen

### ISSUE THREAD

**Issue by CreativeKittens** [devboloji/Infinix-Hackintosh-Opencore-Guide#28]
Hello, i wanted to ask a question sir,

I got grey screen when im trying to install the os, 

i don't think your efi is the problem tho, cuz i have succeed installing it on my machine before, 

im using offline installation method, i don't think the os image that i download is corrupted either cuz i have succeed flashing it to usb drive using etcher,

this is happend after i pick 'install mac os monterey' i the boot menu, but it turn tobe grey screen instead of entering recovery mode do you have any idea what causing it, 

Thank you

![IMG_20230102_162650.jpg](https://user-images.githubusercontent.com/114196216/210214119-1dbe7dc2-9a0c-44ef-a0c1-b26cc195fbc6.jpg)

**Comment by bunnybavros** [comment]
this happened to me once i tried to messing with my bios.
have you tried to reset the bios yet?

**Comment by devboloji** [comment]
> this happened to me once i tried to messing with my bios.
> have you tried to reset the bios yet?

@CreativeKittens

**Comment by devboloji** [comment]
@bunnybavros oww really, Its looking like there is an issue with my EFI(8.7 open core) not with the bios. I will fix it in next update.

**Comment by devboloji** [comment]
Read the changelog of this [Release](https://github.com/devboloji/Infinix-Hackintosh-Opencore-Guide/releases/tag/vfinal) and go on with installation. it will definitely fixes your issue. sorry for the interruption, I will fix it in the next update.

**Comment by bunnybavros** [comment]
I guess? haha.
I was reinstalling the Hackintosh and messing with my bios setting and they turned to pure grey, I remembered that I have changed the EFI too once this happened.

maybe messing with the BIOS caused this might not be true.

**Comment by CreativeKittens** [comment]
> @bunnybavros oww really, Its looking like there is an issue with my EFI(8.7 open core) not with the bios. I will fix it in next update.

I don't think so bro, cuz i have tried using your old efi 0.8.5 opencore still give me grey screen, and i have once succeeded install using your latest efi

**Comment by CreativeKittens** [comment]
> > this happened to me once i tried to messing with my bios.
> > have you tried to reset the bios yet?
> 
> @CreativeKittens 

I have not tried reset the bios, will try it tho

**Comment by devboloji** [comment]
@CreativeKittens Did you copy the 8.5 EFI to usb and tried reseting NVRAM. Resetting NVRAM is must ..

**Comment by CreativeKittens** [comment]
> @CreativeKittens Did you copy the 8.5 EFI to usb and tried reseting NVRAM. Resetting NVRAM is must ..

Yes, i have but still no luck, i will try rest the bios and follow your tutorial from the beginning

**Comment by bunnybavros** [comment]
Have you figured out the problem yet, by the way?
What has been successful for you?

**Comment by bunnybavros** [comment]
Have you solved the problem yet, by the way?
Does it worked for you?
