### ISSUE TITLE
Fusion drive

### ISSUE THREAD

**Issue by rayqusa** [devboloji/Infinix-Hackintosh-Opencore-Guide#29]
since inbook1 has 2 NVME slots. does anyone try Fusion drive?
thank you

**Comment by bunnybavros** [comment]
Isn't you need **only m.2 type** to expand the storage?
I dont think that Fusion drive would work. Correct me if I misunderstood.

**Comment by rayqusa** [comment]
oh, so fusion cant be applied on 2 NVMe. The req is assigning primary and secondary drives only.
