### ISSUE TITLE
On Infinix INBook X1 Neo?

### ISSUE THREAD

**Issue by Laptop-Github** [devboloji/Infinix-Hackintosh-Opencore-Guide#36]
Anyway to make it work it on x1 neo as it has a Celeron N5100 processor? I read somewhere on wiki about intel graphic technology page that the graphics used in N5100 are quite similar to intel 10th gen mobile processors. I tried the INBook x1 EFI on x1 neo and it booted to some kind of terminal, similar to the found in grub terminal. Would be very helpful if you can make it work on X1 Neo.

**Comment by devboloji** [comment]
@Laptop-Github hello ji,  let's talk about it ping me on telegram. And report me with some info and pictures of what showing on screen.
