### ISSUE TITLE
Wifi, Bluetooth not working in sequoia

### ISSUE THREAD

**Issue by MonuCarpenter** [devboloji/Infinix-Hackintosh-Opencore-Guide#40]
I had updated my laptop to sequoia from sonoma, everything works except the bluetooth and wifi, 

![Screenshot 2024-10-05 at 2 53 14 AM](https://github.com/user-attachments/assets/f7d0cd52-4187-45e2-98bf-d5d1ba97775b)
![Screenshot 2024-10-05 at 9 55 04 PM](https://github.com/user-attachments/assets/4181a01e-e02a-4815-8ebf-1a992686efe8)

ping me if you get any update!

**Comment by devboloji** [comment]
@MonuCarpenter i am waiting for the wifi/bluetooth release for sequoia so i can built for new MACOS version
