### ISSUE TITLE
speaker in front infinix logo is not working

### ISSUE THREAD

**Issue by internetvuser** [devboloji/Infinix-Hackintosh-Opencore-Guide#9]
the speaker in fornt of infinix logo is not working only the 2 speaker under the laptop working

**Comment by devboloji** [comment]
@internetvuser Yeah, I've been thinking that why the sound is low in MacOS. Now, You brought the problem to my attention. Good, I'll try to fix it next update. Thank you.

**Comment by devboloji** [comment]
now the three speakers are working now. You can see the change in the next update
